# Site settings
title: "Lab Notes"
description: "What we learned while building JayHorn."
baseurl: ""
url: "http://jayhorn.github.io/jayhorn"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
paginate_path: "/blog/page:num"
paginate: 3


# Links
links:
  - title: "home"
    url: /blog
  - title: "github"
    url: /
  - title: "rss"
    url: /feed.xml
